[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/service-areas/hubbard"
  to = "/waste-management-service-hubbard"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
